module CompactBasisFunctions

    using ContinuumArrays
    using StaticArrays

    import Base: *
    # QuasiAdjoint is not referenced directly, but the code generated by @simplify
    # expands to a QuasiAdjoint method in this module, so it must be in scope
    import ContinuumArrays: Mul, QMul2, QuasiAdjoint, (..), @simplify

    # extended in basis.jl rather than defined there, so that the packages of the ecosystem
    # share one generic function per accessor instead of one per package. `grid` belongs to
    # ContinuumArrays for the same reason; `nbasis` has no counterpart anywhere and is ours.
    import GeometricBase: basis, degree, nnodes, nodes, order

    export Derivative, ℵ₁

    include("vandermonde_matrix.jl")

    export Basis, basis, nbasis, nodes, nnodes, grid, degree, order

    include("basis.jl")

    export Bernstein, BernsteinDerivative,
           Chebyshev, ChebyshevDerivative,
           ChebyshevT, ChebyshevTDerivative,
           ChebyshevU, ChebyshevUDerivative,
           Lagrange, LagrangeDerivative,
           LagrangeGauß, LagrangeLobatto,
           Legendre, LegendreDerivative

    include("bernstein.jl")
    include("chebyshev.jl")
    include("lagrange.jl")
    include("legendre.jl")

end
